# Generated by Django 3.1.6 on 2021-06-26 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('address', models.CharField(max_length=64)),
                ('email', models.CharField(default='', max_length=50)),
                ('number', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user01', models.CharField(default='', max_length=50)),
                ('email01', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_event', models.CharField(default='', max_length=50)),
                ('your_place', models.CharField(default='', max_length=50)),
                ('partcipant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bosrayList.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catetype', models.CharField(default='', max_length=50)),
                ('your_kilometer', models.CharField(default='', max_length=50)),
                ('your_gender', models.CharField(default='', max_length=50)),
                ('team', models.CharField(default='', max_length=50)),
                ('yourage', models.CharField(default='', max_length=50)),
                ('your_name', models.CharField(default='', max_length=50)),
                ('partcipant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bosrayList.participant')),
            ],
        ),
    ]
