# Generated by Django 3.1.6 on 2021-05-03 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bosrayList', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='empid',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='namestudent',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='profname',
            new_name='kilometer',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='sid',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='violation',
        ),
    ]
